name: iris_test
channels:
  - defaults
  - conda-forge
  - atonarp
dependencies:
  - python=3.11
  - uproot
  - pandas
  - numpy
  - tensorflow
  - seaborn
  - jupyter
  - cernopendata-client
  - fsspec-xrootd
  - atlasopenmagic
  - aiohttp
  